
services:
  backend:
    build: ./support-agent
    ports:
      - "8000:8000"
    env_file:
      - ./support-agent/.env
    volumes:
      - ./support-agent/profile_uploads:/app/profile_uploads
    depends_on:
      - db

  frontend:
    build: ./support-system-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: support_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin00
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
